/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {

}
// for type re-export
declare global {
  // @ts-ignore
  export type * as yup from 'yup'
  import('yup')
  // @ts-ignore
  export type { Dispatch, SetStateAction, HTMLProps, HTMLAttributes, ComponentType, ReactNode } from 'react'
  import('react')
}
